#!/bin/bash
# vim: set ft=sh

set -e -u -x

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

BUILD_DIR=$PWD/built-resource

cd $GOPATH/src/github.com/concourse/s3-resource

go install ./vendor/github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -skipPackage integration -race -r -p "$@"
echo "Skipping integration tests. Go see upstream for those test runs https://ci.concourse.ci/teams/main/pipelines/resources/jobs/s3-resource/builds/4"

./scripts/build

cp -a assets/ Dockerfile $BUILD_DIR
